# Generated by Django 4.2.7 on 2023-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0002_boardgame_date_added_boardgame_genre_boardgame_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='genre',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
