# Generated by Django 4.2.7 on 2023-11-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0003_alter_boardgame_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameloan',
            options={'ordering': ['-loan_date']},
        ),
    ]
