# Generated by Django 4.2.7 on 2023-11-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0004_alter_gameloan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
