# Generated by Django 4.2.7 on 2023-11-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0005_boardgame_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name': 'Board game'},
        ),
    ]
