# Generated by Django 4.2.7 on 2023-11-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_app', '0006_alter_boardgame_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='loaned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
