# Generated by Django 4.2.7 on 2023-11-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0008_boardgamereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameLoan',
        ),
    ]
