# Generated by Django 4.2.5 on 2023-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0010_alter_boardgamereview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='date_loaned',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
