# Generated by Django 4.2.5 on 2023-11-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0011_boardgame_date_loaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='max_players',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='play_time',
            field=models.FloatField(default=1.0),
        ),
    ]
