# Generated by Django 4.2.7 on 2023-11-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0012_boardgame_max_players_boardgame_play_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardGamer',
        ),
    ]
